/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.mifos.conventions.gradle.workflow.generator.example;

import org.mifos.conventions.gradle.workflow.generator.example.models.CashierData;
import org.jspecify.annotations.Nullable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;



@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.24.0")
public interface CashiersApi {

    /**
     * GET /v1/cashiers : List Cashiers
     *
     * @param officeId  (optional)
     * @param tellerId  (optional)
     * @param staffId  (optional)
     * @param date  (optional)
     * @return default response (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/v1/cashiers",
        accept = { "application/json" }
    )
    ResponseEntity<List<CashierData>> retrieveAllCashiers(
         @RequestParam(value = "officeId", required = false) Optional<Long> officeId,
         @RequestParam(value = "tellerId", required = false) Optional<Long> tellerId,
         @RequestParam(value = "staffId", required = false) Optional<Long> staffId,
         @RequestParam(value = "date", required = false) Optional<String> date
    );

}
